path: /Users/johnomole/Desktop/pacaba/datasets # dataset root dir
train: ParkingCarsDataset/yolo/train/
val: ParkingCarsDataset/yolo/val
test: ParkingCarsDataset/yolo/test

# Classes
names:
  0: vehicle
